project:
  type: book
  output-dir: docs
book:
  title: "Modelos Mixtos"
  author: "Luis A. Barboza"
  date: "8/30/2024"
  chapters:
    - index.qmd
    - introduccion.qmd
    - MLMbasicos.qmd
    - MLMavanzados.qmd
    - cap16.qmd
    - cap17a.qmd
    - cap17b.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

