project:
  type: book

book:
  title: "Modelos Mixtos"
  author: "Luis A. Barboza"
  date: "8/30/2024"
  chapters:
    - index.qmd
    - introduccion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

